# Generated by Django 3.0.4 on 2020-03-16 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('seats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='theater.Movie')),
                ('room', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='theater.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=255)),
                ('timeslot', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='theater.TimeSlot')),
            ],
        ),
    ]
